jobs:
  build:
    docker:
      - image: cimg/base:2020.01
#    machine:
#      image: ubuntu-2004:202107-02
    resource_class: medium

    steps:
      - checkout
      - run:
          name: Install debugging utils
          command: |
            sudo apt-get update -y

      - run:
          name: Pull license
          command: |
            echo ${pystardog_license} | base64 --decode  > ~/project/dockerfiles/stardog-license-key.bin

     - setup_remote_docker

      - run:
          name: Start containers and run tests
          no_output_timeout: 30m
          # docker-compose up --exit-code-from tests
          command: |
            set -x
            docker-compose up -d




