jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: large

    steps:
      - checkout
      - run:
          name: Install debugging utils
          command: |
            sudo apt-get update -y

      - run:
          name: Pull license
          command: |
            echo ${pystardog_license} | base64 --decode  > ~/project/dockerfiles/stardog-license-key.bin

#     - setup_remote_docker

      - run:
          name: Start containers and run tests
          no_output_timeout: 30m
          command: |
            set -x
            docker-compose up #--exit-code-from tests



